### ISSUE TITLE
store card 2 (sc2)

### ISSUE THREAD

**Issue by ashraffouda** [ashraffouda/org_dev1#2]
- [ ] sc2: issue2 sc1 now sc2 #4
- [x] sc2: issue3 sc2 now sc1 #5
- [ ] sc2: issue4 sc2 #6
- [ ] sc2: bug is this #8
- [ ] sc2: bug xx #11
